code --install-extension albymor.increment-selection
code --install-extension attilabuti.vscode-mjml
code --install-extension bierner.comment-tagged-templates
code --install-extension dakara.transformer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension faustinoaq.crystal-lang
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension GitHub.vscode-pull-request-github
code --install-extension HookyQR.beautify
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension mtxr.sqltools
code --install-extension skyapps.fish-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension zhuangtongfa.material-theme
