code --install-extension AugusteRame.zls-vscode
code --install-extension BenFradet.vscode-unison
code --install-extension bierner.comment-tagged-templates
code --install-extension bierner.markdown-mermaid
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension bungcip.better-toml
code --install-extension chenglou92.rescript-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension fisheva.eva-theme
code --install-extension flowtype.flow-for-vscode
code --install-extension foam.foam-vscode
code --install-extension freebroccolo.reasonml
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension hashicorp.terraform
code --install-extension haskell.haskell
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension justusadam.language-haskell
code --install-extension koka.language-koka
code --install-extension kortina.vscode-markdown-notes
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.Theme-TomorrowKit
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nrwl.angular-console
code --install-extension Orta.vscode-jest
code --install-extension philipbe.theme-gray-matter
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension silvenon.mdx
code --install-extension skyapps.fish-vscode
code --install-extension statelyai.stately-vscode
code --install-extension stkb.rewrap
code --install-extension tchayen.markdown-links
code --install-extension tiehuis.zig
code --install-extension vadimcn.vscode-lldb
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wingrunr21.vscode-ruby
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
